---
name: Docker Image CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            SETTINGS_XML_USERNAME=${{ secrets.SETTINGS_XML_USERNAME }}
            SETTINGS_XML_PASSWORD=${{ secrets.SETTINGS_XML_PASSWORD }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            jorisheadease/kt2-domain-admin:${{ steps.date.outputs.date }}
            jorisheadease/kt2-domain-admin:latest
